"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CARDS = exports.CATEGORIES = void 0;
const URL_IMG = 'https://res.cloudinary.com/dkuf8yc7c/image/upload/v1626337146/EFK/';
const URL_AUDIO = 'https://res.cloudinary.com/dkuf8yc7c/video/upload/v1626336985/EFK/';
exports.CATEGORIES = [
    'Action (set A)',
    'Action (set B)',
    'Vegetables',
    'Transport',
    'Animal (set A)',
    'Animal (set B)',
    'Clothes',
    'Emotions',
];
exports.CARDS = [
    [
        {
            word: 'cry',
            translation: 'плакать',
            image: `${URL_IMG}img/cry.jpg`,
            audioSrc: `${URL_AUDIO}audio/cry.mp3`,
            train: 0,
            incorrect: 0,
            correct: 0,
        },
        {
            word: 'dance',
            translation: 'танцевать',
            image: `${URL_IMG}img/dance.jpg`,
            audioSrc: `${URL_AUDIO}audio/dance.mp3`,
            train: 0,
            incorrect: 0,
            correct: 0,
        },
        {
            word: 'dive',
            translation: 'нырять',
            image: `${URL_IMG}img/dive.jpg`,
            audioSrc: `${URL_AUDIO}audio/dive.mp3`,
            train: 0,
            incorrect: 0,
            correct: 0,
        },
        {
            word: 'draw',
            translation: 'рисовать',
            image: `${URL_IMG}img/draw.jpg`,
            audioSrc: `${URL_AUDIO}audio/draw.mp3`,
            train: 0,
            incorrect: 0,
            correct: 0,
        },
        {
            word: 'fish',
            translation: 'ловить рыбу',
            image: `${URL_IMG}img/fish.jpg`,
            audioSrc: `${URL_AUDIO}audio/fish.mp3`,
            train: 0,
            incorrect: 0,
            correct: 0,
        },
        {
            word: 'fly',
            translation: 'летать',
            image: `${URL_IMG}img/fly.jpg`,
            audioSrc: `${URL_AUDIO}audio/fly.mp3`,
            train: 0,
            incorrect: 0,
            correct: 0,
        },
        {
            word: 'hug',
            translation: 'обнимать',
            image: `${URL_IMG}img/hug.jpg`,
            audioSrc: `${URL_AUDIO}audio/hug.mp3`,
            train: 0,
            incorrect: 0,
            correct: 0,
        },
        {
            word: 'jump',
            translation: 'прыгать',
            image: `${URL_IMG}img/jump.jpg`,
            audioSrc: `${URL_AUDIO}audio/jump.mp3`,
            train: 0,
            incorrect: 0,
            correct: 0,
        },
    ],
    [
        {
            word: 'open',
            translation: 'открывать',
            image: `${URL_IMG}img/open.jpg`,
            audioSrc: `${URL_AUDIO}audio/open.mp3`,
            train: 0,
            incorrect: 0,
            correct: 0,
        },
        {
            word: 'play',
            translation: 'играть',
            image: `${URL_IMG}img/play.jpg`,
            audioSrc: `${URL_AUDIO}audio/play.mp3`,
            train: 0,
            incorrect: 0,
            correct: 0,
        },
        {
            word: 'point',
            translation: 'указывать',
            image: `${URL_IMG}img/point.jpg`,
            audioSrc: `${URL_AUDIO}audio/point.mp3`,
            train: 0,
            incorrect: 0,
            correct: 0,
        },
        {
            word: 'ride',
            translation: 'ездить',
            image: `${URL_IMG}img/ride.jpg`,
            audioSrc: `${URL_AUDIO}audio/ride.mp3`,
            train: 0,
            incorrect: 0,
            correct: 0,
        },
        {
            word: 'run',
            translation: 'бегать',
            image: `${URL_IMG}img/run.jpg`,
            audioSrc: `${URL_AUDIO}audio/run.mp3`,
            train: 0,
            incorrect: 0,
            correct: 0,
        },
        {
            word: 'sing',
            translation: 'петь',
            image: `${URL_IMG}img/sing.jpg`,
            audioSrc: `${URL_AUDIO}audio/sing.mp3`,
            train: 0,
            incorrect: 0,
            correct: 0,
        },
        {
            word: 'skip',
            translation: 'пропускать, прыгать',
            image: `${URL_IMG}img/skip.jpg`,
            audioSrc: `${URL_AUDIO}audio/skip.mp3`,
            train: 0,
            incorrect: 0,
            correct: 0,
        },
        {
            word: 'swim',
            translation: 'плавать',
            image: `${URL_IMG}img/swim.jpg`,
            audioSrc: `${URL_AUDIO}audio/swim.mp3`,
            train: 0,
            incorrect: 0,
            correct: 0,
        },
    ],
    [
        {
            word: 'vegetables',
            translation: 'овощи',
            image: `${URL_IMG}img/vegetables.jpg`,
            audioSrc: `${URL_AUDIO}audio/vegetables.mp3`,
            train: 0,
            incorrect: 0,
            correct: 0,
        },
        {
            word: 'onion',
            translation: 'лук',
            image: `${URL_IMG}img/onion.jpg`,
            audioSrc: `${URL_AUDIO}audio/onion.mp3`,
            train: 0,
            incorrect: 0,
            correct: 0,
        },
        {
            word: 'potato',
            translation: 'картофель',
            image: `${URL_IMG}img/potato.jpg`,
            audioSrc: `${URL_AUDIO}audio/potato.mp3`,
            train: 0,
            incorrect: 0,
            correct: 0,
        },
        {
            word: 'radish',
            translation: 'редис',
            image: `${URL_IMG}img/radish.jpg`,
            audioSrc: `${URL_AUDIO}audio/radish.mp3`,
            train: 0,
            incorrect: 0,
            correct: 0,
        },
        {
            word: 'carrot',
            translation: 'морковь',
            image: `${URL_IMG}img/carrot.jpg`,
            audioSrc: `${URL_AUDIO}audio/carrot.mp3`,
            train: 0,
            incorrect: 0,
            correct: 0,
        },
        {
            word: 'cabbage',
            translation: 'капуста',
            image: `${URL_IMG}img/cabbage.jpg`,
            audioSrc: `${URL_AUDIO}audio/cabbage.mp3`,
            train: 0,
            incorrect: 0,
            correct: 0,
        },
        {
            word: 'pumpkin',
            translation: 'тыква',
            image: `${URL_IMG}img/pumpkin.jpg`,
            audioSrc: `${URL_AUDIO}audio/pumpkin.mp3`,
            train: 0,
            incorrect: 0,
            correct: 0,
        },
        {
            word: 'tomato',
            translation: 'помидор',
            image: `${URL_IMG}img/tomato.jpg`,
            audioSrc: `${URL_AUDIO}audio/tomato.mp3`,
            train: 0,
            incorrect: 0,
            correct: 0,
        },
    ],
    [
        {
            word: 'transport',
            translation: 'транспорт',
            image: `${URL_IMG}img/transport.jpg`,
            audioSrc: `${URL_AUDIO}audio/transport.mp3`,
            train: 0,
            incorrect: 0,
            correct: 0,
        },
        {
            word: 'car',
            translation: 'автомобиль',
            image: `${URL_IMG}img/car.jpg`,
            audioSrc: `${URL_AUDIO}audio/car.mp3`,
            train: 0,
            incorrect: 0,
            correct: 0,
        },
        {
            word: 'bus',
            translation: 'автобус',
            image: `${URL_IMG}img/bus.jpg`,
            audioSrc: `${URL_AUDIO}audio/bus.mp3`,
            train: 0,
            incorrect: 0,
            correct: 0,
        },
        {
            word: 'motorbike',
            translation: 'мотоцикл',
            image: `${URL_IMG}img/motorbike.jpg`,
            audioSrc: `${URL_AUDIO}audio/motorbike.mp3`,
            train: 0,
            incorrect: 0,
            correct: 0,
        },
        {
            word: 'train',
            translation: 'поезд',
            image: `${URL_IMG}img/train.jpg`,
            audioSrc: `${URL_AUDIO}audio/train.mp3`,
            train: 0,
            incorrect: 0,
            correct: 0,
        },
        {
            word: 'trolleybus',
            translation: 'троллейбус',
            image: `${URL_IMG}img/trolleybus.jpg`,
            audioSrc: `${URL_AUDIO}audio/trolleybus.mp3`,
            train: 0,
            incorrect: 0,
            correct: 0,
        },
        {
            word: 'tram',
            translation: 'трамвай',
            image: `${URL_IMG}img/tram.jpg`,
            audioSrc: `${URL_AUDIO}audio/tram.mp3`,
            train: 0,
            incorrect: 0,
            correct: 0,
        },
        {
            word: 'bicycle',
            translation: 'велосипед',
            image: `${URL_IMG}img/bicycle.jpg`,
            audioSrc: `${URL_AUDIO}audio/bicycle.mp3`,
            train: 0,
            incorrect: 0,
            correct: 0,
        },
    ],
    [
        {
            word: 'cat',
            translation: 'кот',
            image: `${URL_IMG}img/cat.jpg`,
            audioSrc: `${URL_AUDIO}audio/cat.mp3`,
            train: 0,
            incorrect: 0,
            correct: 0,
        },
        {
            word: 'chick',
            translation: 'цыплёнок',
            image: `${URL_IMG}img/chick.jpg`,
            audioSrc: `${URL_AUDIO}audio/chick.mp3`,
            train: 0,
            incorrect: 0,
            correct: 0,
        },
        {
            word: 'chicken',
            translation: 'курица',
            image: `${URL_IMG}img/chicken.jpg`,
            audioSrc: `${URL_AUDIO}audio/chicken.mp3`,
            train: 0,
            incorrect: 0,
            correct: 0,
        },
        {
            word: 'dog',
            translation: 'собака',
            image: `${URL_IMG}img/dog.jpg`,
            audioSrc: `${URL_AUDIO}audio/dog.mp3`,
            train: 0,
            incorrect: 0,
            correct: 0,
        },
        {
            word: 'horse',
            translation: 'лошадь',
            image: `${URL_IMG}img/horse.jpg`,
            audioSrc: `${URL_AUDIO}audio/horse.mp3`,
            train: 0,
            incorrect: 0,
            correct: 0,
        },
        {
            word: 'pig',
            translation: 'свинья',
            image: `${URL_IMG}img/pig.jpg`,
            audioSrc: `${URL_AUDIO}audio/pig.mp3`,
            train: 0,
            incorrect: 0,
            correct: 0,
        },
        {
            word: 'rabbit',
            translation: 'кролик',
            image: `${URL_IMG}img/rabbit.jpg`,
            audioSrc: `${URL_AUDIO}audio/rabbit.mp3`,
            train: 0,
            incorrect: 0,
            correct: 0,
        },
        {
            word: 'sheep',
            translation: 'овца',
            image: `${URL_IMG}img/sheep.jpg`,
            audioSrc: `${URL_AUDIO}audio/sheep.mp3`,
            train: 0,
            incorrect: 0,
            correct: 0,
        },
    ],
    [
        {
            word: 'bird',
            translation: 'птица',
            image: `${URL_IMG}img/bird.jpg`,
            audioSrc: `${URL_AUDIO}audio/bird.mp3`,
            train: 0,
            incorrect: 0,
            correct: 0,
        },
        {
            word: 'fish',
            translation: 'рыба',
            image: `${URL_IMG}img/fish1.jpg`,
            audioSrc: `${URL_AUDIO}audio/fish.mp3`,
            train: 0,
            incorrect: 0,
            correct: 0,
        },
        {
            word: 'frog',
            translation: 'жаба',
            image: `${URL_IMG}img/frog.jpg`,
            audioSrc: `${URL_AUDIO}audio/frog.mp3`,
            train: 0,
            incorrect: 0,
            correct: 0,
        },
        {
            word: 'giraffe',
            translation: 'жирафа',
            image: `${URL_IMG}img/giraffe.jpg`,
            audioSrc: `${URL_AUDIO}audio/giraffe.mp3`,
            train: 0,
            incorrect: 0,
            correct: 0,
        },
        {
            word: 'lion',
            translation: 'лев',
            image: `${URL_IMG}img/lion.jpg`,
            audioSrc: `${URL_AUDIO}audio/lion.mp3`,
            train: 0,
            incorrect: 0,
            correct: 0,
        },
        {
            word: 'mouse',
            translation: 'мышь',
            image: `${URL_IMG}img/mouse.jpg`,
            audioSrc: `${URL_AUDIO}audio/mouse.mp3`,
            train: 0,
            incorrect: 0,
            correct: 0,
        },
        {
            word: 'turtle',
            translation: 'черепаха',
            image: `${URL_IMG}img/turtle.jpg`,
            audioSrc: `${URL_AUDIO}audio/turtle.mp3`,
            train: 0,
            incorrect: 0,
            correct: 0,
        },
        {
            word: 'dolphin',
            translation: 'дельфин',
            image: `${URL_IMG}img/dolphin.jpg`,
            audioSrc: `${URL_AUDIO}audio/dolphin.mp3`,
            train: 0,
            incorrect: 0,
            correct: 0,
        },
    ],
    [
        {
            word: 'skirt',
            translation: 'юбка',
            image: `${URL_IMG}img/skirt.jpg`,
            audioSrc: `${URL_AUDIO}audio/skirt.mp3`,
            train: 0,
            incorrect: 0,
            correct: 0,
        },
        {
            word: 'pants',
            translation: 'брюки',
            image: `${URL_IMG}img/pants.jpg`,
            audioSrc: `${URL_AUDIO}audio/pants.mp3`,
            train: 0,
            incorrect: 0,
            correct: 0,
        },
        {
            word: 'blouse',
            translation: 'блузка',
            image: `${URL_IMG}img/blouse.jpg`,
            audioSrc: `${URL_AUDIO}audio/blouse.mp3`,
            train: 0,
            incorrect: 0,
            correct: 0,
        },
        {
            word: 'dress',
            translation: 'платье',
            image: `${URL_IMG}img/dress.jpg`,
            audioSrc: `${URL_AUDIO}audio/dress.mp3`,
            train: 0,
            incorrect: 0,
            correct: 0,
        },
        {
            word: 'boot',
            translation: 'ботинок',
            image: `${URL_IMG}img/boot.jpg`,
            audioSrc: `${URL_AUDIO}audio/boot.mp3`,
            train: 0,
            incorrect: 0,
            correct: 0,
        },
        {
            word: 'shirt',
            translation: 'рубашка',
            image: `${URL_IMG}img/shirt.jpg`,
            audioSrc: `${URL_AUDIO}audio/shirt.mp3`,
            train: 0,
            incorrect: 0,
            correct: 0,
        },
        {
            word: 'coat',
            translation: 'пальто',
            image: `${URL_IMG}img/coat.jpg`,
            audioSrc: `${URL_AUDIO}audio/coat.mp3`,
            train: 0,
            incorrect: 0,
            correct: 0,
        },
        {
            word: 'shoe',
            translation: 'туфли',
            image: `${URL_IMG}img/shoe.jpg`,
            audioSrc: `${URL_AUDIO}audio/shoe.mp3`,
            train: 0,
            incorrect: 0,
            correct: 0,
        },
    ],
    [
        {
            word: 'sad',
            translation: 'грустный',
            image: `${URL_IMG}img/sad.jpg`,
            audioSrc: `${URL_AUDIO}audio/sad.mp3`,
            train: 0,
            incorrect: 0,
            correct: 0,
        },
        {
            word: 'angry',
            translation: 'сердитый',
            image: `${URL_IMG}img/angry.jpg`,
            audioSrc: `${URL_AUDIO}audio/angry.mp3`,
            train: 0,
            incorrect: 0,
            correct: 0,
        },
        {
            word: 'happy',
            translation: 'счастливый',
            image: `${URL_IMG}img/happy.jpg`,
            audioSrc: `${URL_AUDIO}audio/happy.mp3`,
            train: 0,
            incorrect: 0,
            correct: 0,
        },
        {
            word: 'tired',
            translation: 'уставший',
            image: `${URL_IMG}img/tired.jpg`,
            audioSrc: `${URL_AUDIO}audio/tired.mp3`,
            train: 0,
            incorrect: 0,
            correct: 0,
        },
        {
            word: 'surprised',
            translation: 'удивлённый',
            image: `${URL_IMG}img/surprised.jpg`,
            audioSrc: `${URL_AUDIO}audio/surprised.mp3`,
            train: 0,
            incorrect: 0,
            correct: 0,
        },
        {
            word: 'scared',
            translation: 'испуганный',
            image: `${URL_IMG}img/scared.jpg`,
            audioSrc: `${URL_AUDIO}audio/scared.mp3`,
            train: 0,
            incorrect: 0,
            correct: 0,
        },
        {
            word: 'smile',
            translation: 'улыбка',
            image: `${URL_IMG}img/smile.jpg`,
            audioSrc: `${URL_AUDIO}audio/smile.mp3`,
            train: 0,
            incorrect: 0,
            correct: 0,
        },
        {
            word: 'laugh',
            translation: 'смех',
            image: `${URL_IMG}img/laugh.jpg`,
            audioSrc: `${URL_AUDIO}audio/laugh.mp3`,
            train: 0,
            incorrect: 0,
            correct: 0,
        },
    ],
];
//# sourceMappingURL=category.js.map